name: Build
on:
  pull_request:
    paths-ignore:
      - ".editorconfig"
      - "LICENSE"
      - "**.md"
  push:
    paths-ignore:
      - ".editorconfig"
      - "LICENSE"
      - "**.md"
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    name: asdf plugin test
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: tab --version
